package stud.euktop.domain.model.common

// domain/src/main/java/stud/euktop/domain/model/common/DataError.kt
sealed class DataError : Throwable() {
    data class HttpError(val code: Int, override val message: String?) : DataError()
    data class NetworkConnection(override val message: String?) : DataError()
    object EmptyBody : DataError()
    data class Unknown(override val message: String?) : DataError()
    data class SessionContextNotSet(override val message: String?) : DataError()
    data class InvalidCredentials(override val message: String?) : DataError()
    data class UserNotFound(override val message: String?) : DataError()
    data class UserDeleted(override val message: String?) : DataError()
    data class UserNotConfirmed(override val message: String?) : DataError()
    data class UserBlocked(override val message: String?) : DataError()
    data class ClassTimeOverlap(override val message: String?) : DataError()
    data class PermissionOutOfRange(override val message: String?) : DataError()
    data class MultiplePrimaryTeachers(override val message: String?) : DataError()
    data class TeacherCannotTeachSubject(override val message: String?) : DataError()
    data class StudentNotInClass(override val message: String?) : DataError()
    data class RecordAlreadyFixed(override val message: String?) : DataError()
    data class NoPermissionToGrade(override val message: String?) : DataError()
    data class FieldRequired(override val message: String?) : DataError()
    data class UserNotExist(override val message: String?) : DataError()
    data class NoPermissionToManageUser(override val message: String?) : DataError()
    data class RecordNotFound(override val message: String?) : DataError()
    data class SchoolNotFound(override val message: String?) : DataError()
    data class ClassNotFound(override val message: String?) : DataError()
    data class SubjectNotFound(override val message: String?) : DataError()
    data class TeacherNotFound(override val message: String?) : DataError()
    data class UniqueViolation(override val message: String?) : DataError()
    data class ForeignKeyViolation(override val message: String?) : DataError()
    data class RecordAlreadyExists(override val message: String?) : DataError()
    data class CannotDeleteClassWithStudents(override val message: String?) : DataError()
    data class CannotDeleteClassWithLessons(override val message: String?) : DataError()
    data class RoomNotBelongsToSchool(override val message: String?) : DataError()
    data class TeacherTimeConflict(override val message: String?) : DataError()
    data class ClassTimeConflict(override val message: String?) : DataError()
    data class StartTimeAfterEndTime(override val message: String?) : DataError()
    data class CannotDeleteSchoolWithClasses(override val message: String?) : DataError()
    data class CannotDeleteRoomUsedInLessons(override val message: String?) : DataError()
    data class AccessDenied(override val message: String?) : DataError()
    data class InternalServerError(override val message: String?) : DataError()
}